namespace Tesco.ClubcardProducts.MCA.Web.Common.Entities.Settings
{
    public enum DbConfigurationTypeEnum
    {
        Duplicate_check_fields = 1,
        Mandatory_fields = 2,
        Default_contact_preference = 3,
        Error_message = 4,
        Length_of_the_input_fields = 5,
        Group_Config_Values = 6,
        Holding_dates = 7,
        Profanity_check_fields = 8,
        Prefix = 9,
        Format = 10,
        Join_Route_Code = 11,
        Is_Profanity_Check_Needed = 12,
        Activate_Non_Mailable_in_Duplicate_Check = 13,
        Transactional_Database_Name = 14,
        Preference_Fields = 15,
        ExpiredAccountProcesses = 16,
        Uncontactable_Account = 17,
        Inactive_Account = 18,
        HideJoinFunctionality = 19,
        Activation = 20,
        Baby_Todler_Club_Configuration = 21,
        ShowMyCouponPage = 22,
        UI_Parameter = 23,
        ChinaHiddenFunctionality = 25,
        Unknown26 = 26,
        Send_Preference_Email = 27,
        JoinEmailMandatory = 28,
        EmailLinkExpirationTime = 29,
        ColMonthName = 30,
        SecurityCheck = 31,
        EmailNotification = 34,
        HomePageStamps = 35,
        Unknown36 = 36,
        Unknown37 = 37,
        Unknown38 = 38,
        Unknown39 = 39,
        Unknown40 = 40,
        Unknown41 = 41,
        Unknown42 = 42,
        Unknown43 = 43,
        Unknown44 = 44,
        Unknown45 = 45,
        AppSettings = 50,
        DisplayFunctionality =51,
        FieldAbbreviation = 52,
        TextCasing = 53

    }
}
