namespace Tesco.ClubcardProducts.MCA.Web.Common.Entities.Preferences
{
    public enum PreferenceEnum
    {
        Diabetic1 = 1,
        Kosher = 2,
        Halal = 3,
        Vegetarian = 4,
        Teetotal = 5,
        Phone_Contact = 6,
        Tesco_Products = 7,
        Tesco_Partners = 8,
        Customer_Research = 9,
        BA_Miles_Standard = 10,
        Airmiles_Standard = 11,
        Airmiles_Premium = 12,
        Xmas_Saver = 13,
        BA_Miles_Premium = 14,
        Ecoupon = 15,
        Save_Trees = 16,
        Virgin_Atlantic = 17,
        Nut_Allergy = 18,
        Wheat_Allergy = 19,
        Business = 21,
        Home = 22,
        Allow_group_promotions = 23,
        Celiac = 24,
        Lactose = 25,
        Expat = 26,
        Tesco_Group_Mail = 27,
        Tesco_Group_Email = 28,
        Tesco_Group_Phone = 29,
        Tesco_Group_SMS = 30,
        Partner_3rd_Party_Mail = 31,
        Partner_3rd_Party_Email = 32,
        Partner_3rd_Party_Phone = 33,
        Partner_3rd_Party_SMS = 34,
        Research_Mail = 35,
        Research_Email = 36,
        Research_Phone = 37,
        Research_SMS = 38,
        Dietary_1 = 39,
        Dietary_2 = 40,
        Dietary_3 = 41,
        Clubcard_E_Mails = 42,
        E_Mail_Contact = 43,
        Mobile_SMS = 44,
        Post_Contact = 45,
        Post_Large_Print = 46,
        Braille = 47,
        Baby_And_Toddler = 48,
        Bonus_Coupon_Mailing = 49,
        BCM_Mail = 50,
        BCM_EMail = 51,
        BCM_Phone = 52,
        BCM_SMS = 53

    }
}
