//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginIntegration.CustomerIdentityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerIdentity", Namespace="http://schemas.datacontract.org/2004/07/Tesco.com.NGCDecodeCookieService")]
    [System.SerializableAttribute()]
    public partial class CustomerIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DecodedValueField;
        
        private string EncodedvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DecodedValue {
            get {
                return this.DecodedValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DecodedValueField, value) != true)) {
                    this.DecodedValueField = value;
                    this.RaisePropertyChanged("DecodedValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Encodedvalue {
            get {
                return this.EncodedvalueField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodedvalueField, value) != true)) {
                    this.EncodedvalueField = value;
                    this.RaisePropertyChanged("Encodedvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerIdentityService.IDecryptCookieService")]
    public interface IDecryptCookieService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDecryptCookieService/GetDecodedCookie", ReplyAction="http://tempuri.org/IDecryptCookieService/GetDecodedCookieResponse")]
        LoginIntegration.CustomerIdentityService.CustomerIdentity GetDecodedCookie(LoginIntegration.CustomerIdentityService.CustomerIdentity Cust);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDecryptCookieServiceChannel : LoginIntegration.CustomerIdentityService.IDecryptCookieService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DecryptCookieServiceClient : System.ServiceModel.ClientBase<LoginIntegration.CustomerIdentityService.IDecryptCookieService>, LoginIntegration.CustomerIdentityService.IDecryptCookieService {
        
        public DecryptCookieServiceClient() {
        }
        
        public DecryptCookieServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DecryptCookieServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptCookieServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DecryptCookieServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LoginIntegration.CustomerIdentityService.CustomerIdentity GetDecodedCookie(LoginIntegration.CustomerIdentityService.CustomerIdentity Cust) {
            return base.Channel.GetDecodedCookie(Cust);
        }
    }
}
