//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiMethodNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiMethodNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApiMethodNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer.
        /// </summary>
        internal static string bearer {
            get {
                return ResourceManager.GetString("bearer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trn:tesco:cid:97fa99f2-dc85-481e-bab5-67cacca91f16:24ef4fb3-0a74-49ed-99f9-dbf62b84675d.
        /// </summary>
        internal static string client_id {
            get {
                return ResourceManager.GetString("client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cardset.
        /// </summary>
        internal static string createCardSet {
            get {
                return ResourceManager.GetString("createCardSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cardset/may-order-another-card-now/{0}.
        /// </summary>
        internal static string entitledToNewCard {
            get {
                return ResourceManager.GetString("entitledToNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /auth/oauth/v2/token.
        /// </summary>
        internal static string getAccessToken {
            get {
                return ResourceManager.GetString("getAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GetUUIDByCustomerID.
        /// </summary>
        internal static string getCustomerUUID {
            get {
                return ResourceManager.GetString("getCustomerUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string grant_type {
            get {
                return ResourceManager.GetString("grant_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fRa7a5hazuzej?Ke.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oob.
        /// </summary>
        internal static string scope {
            get {
                return ResourceManager.GetString("scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58.
        /// </summary>
        internal static string tokenExpiryTime {
            get {
                return ResourceManager.GetString("tokenExpiryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerEngagementCentre.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trn%3Atesco%3Auid%3Auuid%3A.
        /// </summary>
        internal static string uuidPrefix {
            get {
                return ResourceManager.GetString("uuidPrefix", resourceCulture);
            }
        }
    }
}
