//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigLinks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigLinks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ConfigLinks", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/.
        /// </summary>
        internal static string AAPBack {
            get {
                return ResourceManager.GetString("AAPBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard.aspx#benefit.
        /// </summary>
        internal static string BenefitsAndPrivilages {
            get {
                return ResourceManager.GetString("BenefitsAndPrivilages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesco.com.
        /// </summary>
        internal static string BrowserHeader {
            get {
                return ResourceManager.GetString("BrowserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/boost.
        /// </summary>
        internal static string ClubcardBoostBannerLink {
            get {
                return ResourceManager.GetString("ClubcardBoostBannerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Options-benefits/Home.aspx.
        /// </summary>
        internal static string CSHClickHere {
            get {
                return ResourceManager.GetString("CSHClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/clubcard/smartphones/.
        /// </summary>
        internal static string DownloadAppTellMeMore {
            get {
                return ResourceManager.GetString("DownloadAppTellMeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/eCoupons.asp.
        /// </summary>
        internal static string EHClickHere {
            get {
                return ResourceManager.GetString("EHClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/boost-at-tesco/.
        /// </summary>
        internal static string ExcTescoBigEx {
            get {
                return ResourceManager.GetString("ExcTescoBigEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/boost/.
        /// </summary>
        internal static string ExcTescoBigExchange {
            get {
                return ResourceManager.GetString("ExcTescoBigExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/email-sign-up.
        /// </summary>
        internal static string ExcTescoEmail {
            get {
                return ResourceManager.GetString("ExcTescoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/boost-at-tesco/.
        /// </summary>
        internal static string ExcTescorewards {
            get {
                return ResourceManager.GetString("ExcTescorewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 494720700591406.
        /// </summary>
        internal static string fbappID {
            get {
                return ResourceManager.GetString("fbappID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.tesco.com.
        /// </summary>
        internal static string fbCaption {
            get {
                return ResourceManager.GetString("fbCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your unspent Clubcard vouchers under \&apos;My Clubcard Account\&apos; at www.tesco.com/clubcard.
        /// </summary>
        internal static string fbDescription {
            get {
                return ResourceManager.GetString("fbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/facebook.asp.
        /// </summary>
        internal static string fbLink {
            get {
                return ResourceManager.GetString("fbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I\&apos;ve just discovered Tesco Clubcard vouchers I didn\&apos;t know I had!.
        /// </summary>
        internal static string fbMessage {
            get {
                return ResourceManager.GetString("fbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook - Clubcard - Tesco.com.
        /// </summary>
        internal static string fbName {
            get {
                return ResourceManager.GetString("fbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/account/en-GB/marketing-preferences.
        /// </summary>
        internal static string groupOptOut {
            get {
                return ResourceManager.GetString("groupOptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/Avios.jpg.
        /// </summary>
        internal static string imgAvios {
            get {
                return ResourceManager.GetString("imgAvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/avios_logo.jpg.
        /// </summary>
        internal static string imgAviosLogo {
            get {
                return ResourceManager.GetString("imgAviosLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/baavios.jpg.
        /// </summary>
        internal static string imgBaavios {
            get {
                return ResourceManager.GetString("imgBaavios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/banner.jpg.
        /// </summary>
        internal static string imgBanner {
            get {
                return ResourceManager.GetString("imgBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/cards.jpg.
        /// </summary>
        internal static string imgCards {
            get {
                return ResourceManager.GetString("imgCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/ccemails.jpg.
        /// </summary>
        internal static string imgCcemails {
            get {
                return ResourceManager.GetString("imgCcemails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/christmassavers.jpg.
        /// </summary>
        internal static string imgChristmassavers {
            get {
                return ResourceManager.GetString("imgChristmassavers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/clubcard.gif.
        /// </summary>
        internal static string imgClubcard {
            get {
                return ResourceManager.GetString("imgClubcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/congratulations.png.
        /// </summary>
        internal static string imgCongratulations {
            get {
                return ResourceManager.GetString("imgCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/email.jpg.
        /// </summary>
        internal static string imgEmail {
            get {
                return ResourceManager.GetString("imgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/facebook_logo.jpg.
        /// </summary>
        internal static string imgFacebookLogo {
            get {
                return ResourceManager.GetString("imgFacebookLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/join-header.jpg.
        /// </summary>
        internal static string imgJoinHeader {
            get {
                return ResourceManager.GetString("imgJoinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/post.jpg.
        /// </summary>
        internal static string imgPost {
            get {
                return ResourceManager.GetString("imgPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/print-icon.gif.
        /// </summary>
        internal static string imgPrintIcon {
            get {
                return ResourceManager.GetString("imgPrintIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/receipt-icon.gif.
        /// </summary>
        internal static string imgReceiptIcon {
            get {
                return ResourceManager.GetString("imgReceiptIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/sms.jpg.
        /// </summary>
        internal static string imgSMS {
            get {
                return ResourceManager.GetString("imgSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/Twitter.png.
        /// </summary>
        internal static string imgTwitter {
            get {
                return ResourceManager.GetString("imgTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/Virginatlantic.jpg.
        /// </summary>
        internal static string imgVirginatlantic {
            get {
                return ResourceManager.GetString("imgVirginatlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/VirginFlyingClublogo.jpg.
        /// </summary>
        internal static string imgVirginFlyingClublogo {
            get {
                return ResourceManager.GetString("imgVirginFlyingClublogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/basket.aspx.
        /// </summary>
        internal static string JMBasket {
            get {
                return ResourceManager.GetString("JMBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/perks/.
        /// </summary>
        internal static string JMCCPerks {
            get {
                return ResourceManager.GetString("JMCCPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/calculator.asp.
        /// </summary>
        internal static string JMClubcardBreaks {
            get {
                return ResourceManager.GetString("JMClubcardBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/terms-and-conditions/.
        /// </summary>
        internal static string JMConditions {
            get {
                return ResourceManager.GetString("JMConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/contact/.
        /// </summary>
        internal static string JMContactus {
            get {
                return ResourceManager.GetString("JMContactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/email-sign-up/.
        /// </summary>
        internal static string JMEmailSignup {
            get {
                return ResourceManager.GetString("JMEmailSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/.
        /// </summary>
        internal static string JMExchangeandRewards {
            get {
                return ResourceManager.GetString("JMExchangeandRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/tesco.
        /// </summary>
        internal static string JMFacebook {
            get {
                return ResourceManager.GetString("JMFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/.
        /// </summary>
        internal static string JMFAQS {
            get {
                return ResourceManager.GetString("JMFAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/register/?from=.
        /// </summary>
        internal static string JMFrom {
            get {
                return ResourceManager.GetString("JMFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/.
        /// </summary>
        internal static string JMHelp {
            get {
                return ResourceManager.GetString("JMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/lost-clubcard/.
        /// </summary>
        internal static string JMLostyourClubcard {
            get {
                return ResourceManager.GetString("JMLostyourClubcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/myaccount/.
        /// </summary>
        internal static string JMMyClubcardAccount {
            get {
                return ResourceManager.GetString("JMMyClubcardAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/register/signout.aspx?from=http%3A%2F%2Fwww%2Etesco%2Ecom%2Fclubcard%2F.
        /// </summary>
        internal static string JMSignOut {
            get {
                return ResourceManager.GetString("JMSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/sitemap/.
        /// </summary>
        internal static string JMSitemap {
            get {
                return ResourceManager.GetString("JMSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/about/.
        /// </summary>
        internal static string JMSpendandCollect {
            get {
                return ResourceManager.GetString("JMSpendandCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/terms-and-conditions/.
        /// </summary>
        internal static string JMTandC {
            get {
                return ResourceManager.GetString("JMTandC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com.
        /// </summary>
        internal static string JMTesco {
            get {
                return ResourceManager.GetString("JMTesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/contact/.
        /// </summary>
        internal static string JMTescoCC {
            get {
                return ResourceManager.GetString("JMTescoCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/login.asp.
        /// </summary>
        internal static string JMTescoCCLogin {
            get {
                return ResourceManager.GetString("JMTescoCCLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/sitemap/.
        /// </summary>
        internal static string JMTescoCCSite {
            get {
                return ResourceManager.GetString("JMTescoCCSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/charter/.
        /// </summary>
        internal static string JMTescoChar {
            get {
                return ResourceManager.GetString("JMTescoChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/.
        /// </summary>
        internal static string JMTescoClub {
            get {
                return ResourceManager.GetString("JMTescoClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/collect-spend.
        /// </summary>
        internal static string JMTescoColl {
            get {
                return ResourceManager.GetString("JMTescoColl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com.
        /// </summary>
        internal static string JMTescocom {
            get {
                return ResourceManager.GetString("JMTescocom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/terms-and-conditions/.
        /// </summary>
        internal static string JMTescoConflict {
            get {
                return ResourceManager.GetString("JMTescoConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/emails/.
        /// </summary>
        internal static string JMTescoEmail {
            get {
                return ResourceManager.GetString("JMTescoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/lost-clubcard/.
        /// </summary>
        internal static string JMTescoLost {
            get {
                return ResourceManager.GetString("JMTescoLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/news.asp.
        /// </summary>
        internal static string JMTescoNew {
            get {
                return ResourceManager.GetString("JMTescoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/charter.asp#privacy_policy.
        /// </summary>
        internal static string JMTescoPrivacy {
            get {
                return ResourceManager.GetString("JMTescoPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/rewards/.
        /// </summary>
        internal static string JMTescoReward {
            get {
                return ResourceManager.GetString("JMTescoReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/spend.asp.
        /// </summary>
        internal static string JMTescoSpend {
            get {
                return ResourceManager.GetString("JMTescoSpend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/terms.asp#clubcard_terms.
        /// </summary>
        internal static string JMTescoTerm {
            get {
                return ResourceManager.GetString("JMTescoTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/what.asp.
        /// </summary>
        internal static string JMTescoWhat {
            get {
                return ResourceManager.GetString("JMTescoWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/christmas-savers/.
        /// </summary>
        internal static string JMTescoXmas {
            get {
                return ResourceManager.GetString("JMTescoXmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/TescoOffersMore.
        /// </summary>
        internal static string JMTwitter {
            get {
                return ResourceManager.GetString("JMTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/charter/.
        /// </summary>
        internal static string JMYourprivacy {
            get {
                return ResourceManager.GetString("JMYourprivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.youtube.com/playlist?list=PLB90E16B1F490600F.
        /// </summary>
        internal static string JMYouTube {
            get {
                return ResourceManager.GetString("JMYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=237&amp;amp;amp;in_merch=1&amp;amp;amp;in_merch_title=More+great+Clubcard+rewards&amp;amp;amp;in_merch_name=.
        /// </summary>
        internal static string lnkVoucherBAAvios {
            get {
                return ResourceManager.GetString("lnkVoucherBAAvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2179&amp;amp;amp;in_merch=1&amp;amp;amp;in_merch_title=More+great+Clubcard+rewards&amp;amp;amp;in_merch_name=.
        /// </summary>
        internal static string lnkVoucherVirgin {
            get {
                return ResourceManager.GetString("lnkVoucherVirgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/#lost_clubcard_or_key_fobs.
        /// </summary>
        internal static string LostClubcardLink {
            get {
                return ResourceManager.GetString("LostClubcardLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/#mca_cards.
        /// </summary>
        internal static string MCHFaq {
            get {
                return ResourceManager.GetString("MCHFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=855.
        /// </summary>
        internal static string MLSClubDealTesco {
            get {
                return ResourceManager.GetString("MLSClubDealTesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/restaurants.aspx.
        /// </summary>
        internal static string MLSDealRestaurant {
            get {
                return ResourceManager.GetString("MLSDealRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tescoopticians.com/.
        /// </summary>
        internal static string MLSopticians {
            get {
                return ResourceManager.GetString("MLSopticians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/browse.aspx?N=4294966467.
        /// </summary>
        internal static string MLSPrdBrowse {
            get {
                return ResourceManager.GetString("MLSPrdBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/storelocator/.
        /// </summary>
        internal static string MLSSToreLoc {
            get {
                return ResourceManager.GetString("MLSSToreLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/groceries/.
        /// </summary>
        internal static string MLSTesco {
            get {
                return ResourceManager.GetString("MLSTesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.avios.com/.
        /// </summary>
        internal static string MLSTescoAvios {
            get {
                return ResourceManager.GetString("MLSTescoAvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tescobank.com/personal/finance/insurance/travelins/index.html.
        /// </summary>
        internal static string MLSTescoBank {
            get {
                return ResourceManager.GetString("MLSTescoBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/direct/books/.
        /// </summary>
        internal static string MLSTescoBooks {
            get {
                return ResourceManager.GetString("MLSTescoBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/browse.aspx?N=4294967232.
        /// </summary>
        internal static string MLSTescoBrowse {
            get {
                return ResourceManager.GetString("MLSTescoBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/browse.aspx?N=4294964995.
        /// </summary>
        internal static string MLSTescoClubDeal {
            get {
                return ResourceManager.GetString("MLSTescoClubDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/collect-spend.
        /// </summary>
        internal static string MLSTescoColl {
            get {
                return ResourceManager.GetString("MLSTescoColl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/p.aspx?id=fun.
        /// </summary>
        internal static string MLSTescoDaySearch {
            get {
                return ResourceManager.GetString("MLSTescoDaySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=190.
        /// </summary>
        internal static string MLSTescoDealNum {
            get {
                return ResourceManager.GetString("MLSTescoDealNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=1797.
        /// </summary>
        internal static string MLSTescoDealPrd {
            get {
                return ResourceManager.GetString("MLSTescoDealPrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=185.
        /// </summary>
        internal static string MLSTescoDealPrdt {
            get {
                return ResourceManager.GetString("MLSTescoDealPrdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=184.
        /// </summary>
        internal static string MLSTescoDealProduct {
            get {
                return ResourceManager.GetString("MLSTescoDealProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/direct/.
        /// </summary>
        internal static string MLSTescoDirect {
            get {
                return ResourceManager.GetString("MLSTescoDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/browse.aspx?N=4294964844.
        /// </summary>
        internal static string MLSTescoDPrd {
            get {
                return ResourceManager.GetString("MLSTescoDPrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tesco.com/exchange.
        /// </summary>
        internal static string MLSTescoExchanges {
            get {
                return ResourceManager.GetString("MLSTescoExchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tescobank.com/personal/finance/creditcards/index.html.
        /// </summary>
        internal static string MLSTescoIndex {
            get {
                return ResourceManager.GetString("MLSTescoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/petrolstation/.
        /// </summary>
        internal static string MLSTescoPetrol {
            get {
                return ResourceManager.GetString("MLSTescoPetrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://phone-shop.tesco.com/.
        /// </summary>
        internal static string MLSTescoPhone {
            get {
                return ResourceManager.GetString("MLSTescoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=114.
        /// </summary>
        internal static string MLSTescoPrdD {
            get {
                return ResourceManager.GetString("MLSTescoPrdD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2661.
        /// </summary>
        internal static string MLSTescoPrdDeal {
            get {
                return ResourceManager.GetString("MLSTescoPrdDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=865.
        /// </summary>
        internal static string MLSTescoPrdDealnum {
            get {
                return ResourceManager.GetString("MLSTescoPrdDealnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=111.
        /// </summary>
        internal static string MLSTescoPrdNum {
            get {
                return ResourceManager.GetString("MLSTescoPrdNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=236.
        /// </summary>
        internal static string MLSTescoPrdR {
            get {
                return ResourceManager.GetString("MLSTescoPrdR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2620.
        /// </summary>
        internal static string MLSTescoPrdRR {
            get {
                return ResourceManager.GetString("MLSTescoPrdRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=1802.
        /// </summary>
        internal static string MLSTescoProduct {
            get {
                return ResourceManager.GetString("MLSTescoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/rewards.
        /// </summary>
        internal static string MLSTescoReward {
            get {
                return ResourceManager.GetString("MLSTescoReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/storelocator/.
        /// </summary>
        internal static string MLSTescoStoreLoc {
            get {
                return ResourceManager.GetString("MLSTescoStoreLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.virgin-atlantic.com/en/gb/frequentflyer/spendmiles/index.jsp?cm_mmc=UK%20Display-_-Partner%20site%20promotions-_-Tesco%20online%20statement-_-Aug12.
        /// </summary>
        internal static string MLSTescoVirginIndex {
            get {
                return ResourceManager.GetString("MLSTescoVirginIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/wine/.
        /// </summary>
        internal static string MLSTescoWine {
            get {
                return ResourceManager.GetString("MLSTescoWine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/clubcard/register-my-account/.
        /// </summary>
        internal static string MyAccountTellMeMore {
            get {
                return ResourceManager.GetString("MyAccountTellMeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/clubcard/collect-points/.
        /// </summary>
        internal static string OnlineShopTellMeMore {
            get {
                return ResourceManager.GetString("OnlineShopTellMeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.adobe.com/products/reader.html.
        /// </summary>
        internal static string ORHAdobe {
            get {
                return ResourceManager.GetString("ORHAdobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/#lost_clubcard_or_key_fobs.
        /// </summary>
        internal static string ORHFaq {
            get {
                return ResourceManager.GetString("ORHFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/babyclub.
        /// </summary>
        internal static string PDHBabyMessage {
            get {
                return ResourceManager.GetString("PDHBabyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/register/contactDetails.aspx?vstore=0.
        /// </summary>
        internal static string PDHContactDetails {
            get {
                return ResourceManager.GetString("PDHContactDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/login/en-gb/changepassword/change/.
        /// </summary>
        internal static string PDHTescoPassword {
            get {
                return ResourceManager.GetString("PDHTescoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=236&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string PHAviosMoreInfo {
            get {
                return ResourceManager.GetString("PHAviosMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=236&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string PHAviosOutMoreInfo {
            get {
                return ResourceManager.GetString("PHAviosOutMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=237&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string PHBAMemberMoreInfo {
            get {
                return ResourceManager.GetString("PHBAMemberMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=237&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string PHBAMilesMoreInfo {
            get {
                return ResourceManager.GetString("PHBAMilesMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/babyclub.
        /// </summary>
        internal static string PHBntMoreInfo {
            get {
                return ResourceManager.GetString("PHBntMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/charter/.
        /// </summary>
        internal static string PHCharter {
            get {
                return ResourceManager.GetString("PHCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/christmas-savers/.
        /// </summary>
        internal static string PHChristmasSaversMoreInfo {
            get {
                return ResourceManager.GetString("PHChristmasSaversMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/email-sign-up.
        /// </summary>
        internal static string PHClubcardEmailMoreInfo {
            get {
                return ResourceManager.GetString("PHClubcardEmailMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/clubcard/spend-vouchers/.
        /// </summary>
        internal static string PHClubcardPartners {
            get {
                return ResourceManager.GetString("PHClubcardPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/register/contactPrefs.aspx?vstore=0.
        /// </summary>
        internal static string PHContactPref {
            get {
                return ResourceManager.GetString("PHContactPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/eCoupons.asp.
        /// </summary>
        internal static string PHMoreInformation {
            get {
                return ResourceManager.GetString("PHMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/eCoupons.asp.
        /// </summary>
        internal static string PHMoreInformation1 {
            get {
                return ResourceManager.GetString("PHMoreInformation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/preferences.
        /// </summary>
        internal static string PHPreference {
            get {
                return ResourceManager.GetString("PHPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/terms-and-conditions/.
        /// </summary>
        internal static string PHTerms {
            get {
                return ResourceManager.GetString("PHTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/terms-and-conditions/.
        /// </summary>
        internal static string PHTermsConditions {
            get {
                return ResourceManager.GetString("PHTermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/trees.
        /// </summary>
        internal static string PHTreesMoreInfo {
            get {
                return ResourceManager.GetString("PHTreesMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2179&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string PHVirginAtlanticMoreInfo {
            get {
                return ResourceManager.GetString("PHVirginAtlanticMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2179&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string PHVirginAtlanticMoreInfo1 {
            get {
                return ResourceManager.GetString("PHVirginAtlanticMoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/calculator.asp.
        /// </summary>
        internal static string PntHCalculatorClickhere {
            get {
                return ResourceManager.GetString("PntHCalculatorClickhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/#mca_points.
        /// </summary>
        internal static string PntHFaq {
            get {
                return ResourceManager.GetString("PntHFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/clubcard/help/faqs.
        /// </summary>
        internal static string ReceiptTellMeMore {
            get {
                return ResourceManager.GetString("ReceiptTellMeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/what.asp.
        /// </summary>
        internal static string SMAboutClubcard {
            get {
                return ResourceManager.GetString("SMAboutClubcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/basket.aspx.
        /// </summary>
        internal static string SMBasket {
            get {
                return ResourceManager.GetString("SMBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/perks/.
        /// </summary>
        internal static string SMCCPerks {
            get {
                return ResourceManager.GetString("SMCCPerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/christmas-savers/.
        /// </summary>
        internal static string SMChristmasSavers {
            get {
                return ResourceManager.GetString("SMChristmasSavers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.clubcardbreaks.com/.
        /// </summary>
        internal static string SMClubcardBreaks {
            get {
                return ResourceManager.GetString("SMClubcardBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/collect-spend.
        /// </summary>
        internal static string SMCollectPoints {
            get {
                return ResourceManager.GetString("SMCollectPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/terms-and-conditions/.
        /// </summary>
        internal static string SMConditions {
            get {
                return ResourceManager.GetString("SMConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/contact/.
        /// </summary>
        internal static string SMContact {
            get {
                return ResourceManager.GetString("SMContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/contact/.
        /// </summary>
        internal static string SMContactus {
            get {
                return ResourceManager.GetString("SMContactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/email-sign-up/.
        /// </summary>
        internal static string SMEmailSignup {
            get {
                return ResourceManager.GetString("SMEmailSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/.
        /// </summary>
        internal static string SMExchangeandRewards {
            get {
                return ResourceManager.GetString("SMExchangeandRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/tesco.
        /// </summary>
        internal static string SMFacebook {
            get {
                return ResourceManager.GetString("SMFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/.
        /// </summary>
        internal static string SMFaq {
            get {
                return ResourceManager.GetString("SMFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/help/faqs/.
        /// </summary>
        internal static string SMHelp {
            get {
                return ResourceManager.GetString("SMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/.
        /// </summary>
        internal static string SMHome {
            get {
                return ResourceManager.GetString("SMHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://instagram.com/tescomalaysia.
        /// </summary>
        internal static string SMInstagram {
            get {
                return ResourceManager.GetString("SMInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/.
        /// </summary>
        internal static string SMlogoclubcard {
            get {
                return ResourceManager.GetString("SMlogoclubcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/lost-clubcard/.
        /// </summary>
        internal static string SMLostyourClubcard {
            get {
                return ResourceManager.GetString("SMLostyourClubcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/myaccount/.
        /// </summary>
        internal static string SMMyClubcardAccount {
            get {
                return ResourceManager.GetString("SMMyClubcardAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/news.asp.
        /// </summary>
        internal static string SMNews {
            get {
                return ResourceManager.GetString("SMNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/rewards/.
        /// </summary>
        internal static string SMRewards {
            get {
                return ResourceManager.GetString("SMRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://secure.tesco.com/register/signout.aspx?from=http%3A%2F%2Fwww%2Etesco%2Ecom%2Fclubcard%2F.
        /// </summary>
        internal static string SMSignOut {
            get {
                return ResourceManager.GetString("SMSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/sitemap/.
        /// </summary>
        internal static string SMSitemap {
            get {
                return ResourceManager.GetString("SMSitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/about/.
        /// </summary>
        internal static string SMSpendandCollect {
            get {
                return ResourceManager.GetString("SMSpendandCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/spend.asp.
        /// </summary>
        internal static string SMSpendvouchers {
            get {
                return ResourceManager.GetString("SMSpendvouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com.
        /// </summary>
        internal static string SMTescocom {
            get {
                return ResourceManager.GetString("SMTescocom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com.
        /// </summary>
        internal static string SMTescoDotcom {
            get {
                return ResourceManager.GetString("SMTescoDotcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/TescoOffersMore.
        /// </summary>
        internal static string SMTwitter {
            get {
                return ResourceManager.GetString("SMTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/charter/.
        /// </summary>
        internal static string SMYourprivacy {
            get {
                return ResourceManager.GetString("SMYourprivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.youtube.com/playlist?list=PLB90E16B1F490600F.
        /// </summary>
        internal static string SMYouTube {
            get {
                return ResourceManager.GetString("SMYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/fuelsave/.
        /// </summary>
        internal static string TescoBannerLink {
            get {
                return ResourceManager.GetString("TescoBannerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/fuelsave/.
        /// </summary>
        internal static string TescoFuelSave {
            get {
                return ResourceManager.GetString("TescoFuelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/share?original_referer=&amp;text=I%27ve just discovered Tesco %23Clubcard vouchers I didn%27t know I had! Find your unspent vouchers at &amp;url=http%3A%2F%2Fwww.tesco.com%2Fclubcard.
        /// </summary>
        internal static string twitterlink {
            get {
                return ResourceManager.GetString("twitterlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points/Home.aspx.
        /// </summary>
        internal static string urlStamp1 {
            get {
                return ResourceManager.GetString("urlStamp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCoupon/Home.aspx.
        /// </summary>
        internal static string urlStamp2 {
            get {
                return ResourceManager.GetString("urlStamp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers/Home.aspx.
        /// </summary>
        internal static string urlStamp3 {
            get {
                return ResourceManager.GetString("urlStamp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatestStatement/Home.aspx.
        /// </summary>
        internal static string urlStamp4 {
            get {
                return ResourceManager.GetString("urlStamp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalDetails/Home.aspx.
        /// </summary>
        internal static string urlStamp5 {
            get {
                return ResourceManager.GetString("urlStamp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoostsAtTesco/Home.aspx.
        /// </summary>
        internal static string urlStamp6 {
            get {
                return ResourceManager.GetString("urlStamp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options-benefits/Home.aspx.
        /// </summary>
        internal static string urlStamp7 {
            get {
                return ResourceManager.GetString("urlStamp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderAReplacement/Home.aspx.
        /// </summary>
        internal static string urlStamp8 {
            get {
                return ResourceManager.GetString("urlStamp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChristmasSavers/Home.aspx.
        /// </summary>
        internal static string urlStamp9 {
            get {
                return ResourceManager.GetString("urlStamp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=236&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VHAvios {
            get {
                return ResourceManager.GetString("VHAvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=237&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VHpbaavios {
            get {
                return ResourceManager.GetString("VHpbaavios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2179&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VHpvirgin {
            get {
                return ResourceManager.GetString("VHpvirgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=236&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VHRewadsite {
            get {
                return ResourceManager.GetString("VHRewadsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=237&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VHRewadsite1 {
            get {
                return ResourceManager.GetString("VHRewadsite1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2179&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VHRewadsite2 {
            get {
                return ResourceManager.GetString("VHRewadsite2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/calculator.asp.
        /// </summary>
        internal static string VHTescoMstCard {
            get {
                return ResourceManager.GetString("VHTescoMstCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/lock.png.
        /// </summary>
        internal static string VoucherLock {
            get {
                return ResourceManager.GetString("VoucherLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=236&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VoucherPageLink1 {
            get {
                return ResourceManager.GetString("VoucherPageLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=237&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VoucherPageLink2 {
            get {
                return ResourceManager.GetString("VoucherPageLink2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/deals/product.aspx?R=2179&amp;in_merch=1&amp;in_merch_title=More+great+Clubcard+rewards&amp;in_merch_name=.
        /// </summary>
        internal static string VoucherPageLink3 {
            get {
                return ResourceManager.GetString("VoucherPageLink3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/clubcard/clubcard/calculator.asp.
        /// </summary>
        internal static string VoucherPageLink4 {
            get {
                return ResourceManager.GetString("VoucherPageLink4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers/Home.aspx.
        /// </summary>
        internal static string VoucherUrl {
            get {
                return ResourceManager.GetString("VoucherUrl", resourceCulture);
            }
        }
    }
}
