//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some issue in processing your request, Please try again later!!.
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avios Text message content comes here.
        /// </summary>
        internal static string AviosMessageContent {
            get {
                return ResourceManager.GetString("AviosMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA Avios Text message content comes here.
        /// </summary>
        internal static string BAviosMessageContent {
            get {
                return ResourceManager.GetString("BAviosMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tesco.com/help/privacy-and-cookies/privacy-centre/privacy-policy/.
        /// </summary>
        internal static string CookiePolicyLink {
            get {
                return ResourceManager.GetString("CookiePolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use .
        /// </summary>
        internal static string CookiePopUpMsg {
            get {
                return ResourceManager.GetString("CookiePopUpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (&quot;cookies&quot;) to help give you the best experience on our site and to show you relevant advertising. If you continue to use this site, we&apos;ll assume that you&apos;re happy to receive all cookies..
        /// </summary>
        internal static string CookiePopUpMsg2 {
            get {
                return ResourceManager.GetString("CookiePopUpMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CookiePopUpMsgCloseBtn {
            get {
                return ResourceManager.GetString("CookiePopUpMsgCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cookies and similar technologies.
        /// </summary>
        internal static string CookiePopUpMsgFindOutMore {
            get {
                return ResourceManager.GetString("CookiePopUpMsgFindOutMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string ddlDayResource1 {
            get {
                return ResourceManager.GetString("ddlDayResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ddlHouseholdYearResource1 {
            get {
                return ResourceManager.GetString("ddlHouseholdYearResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select Month-.
        /// </summary>
        internal static string ddlMonthResource1 {
            get {
                return ResourceManager.GetString("ddlMonthResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ddlYearResource1 {
            get {
                return ResourceManager.GetString("ddlYearResource1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your redesigned My Clubcard Account. Please.
        /// </summary>
        internal static string ReskinAdvisingMsg1 {
            get {
                return ResourceManager.GetString("ReskinAdvisingMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        internal static string ReskinAdvisingMsg2 {
            get {
                return ResourceManager.GetString("ReskinAdvisingMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to let us know what you think!.
        /// </summary>
        internal static string ReskinAdvisingMsg3 {
            get {
                return ResourceManager.GetString("ReskinAdvisingMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://j64iyv61.optimalworkshop.com/questions/tesco-1/.
        /// </summary>
        internal static string ReskinAdvisingMsgURL {
            get {
                return ResourceManager.GetString("ReskinAdvisingMsgURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry, your statement video is not available just now.
        /// </summary>
        internal static string SorryMessage {
            get {
                return ResourceManager.GetString("SorryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address did not match, please enter correct email address.
        /// </summary>
        internal static string validatecorrectemail {
            get {
                return ResourceManager.GetString("validatecorrectemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string Validateemailaddress {
            get {
                return ResourceManager.GetString("Validateemailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile numbers did not match, please enter correct mobile numbers.
        /// </summary>
        internal static string validErrorMessage {
            get {
                return ResourceManager.GetString("validErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile phone number.
        /// </summary>
        internal static string ValidMobileNumber {
            get {
                return ResourceManager.GetString("ValidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgin Atlantic Message content comes here.
        /// </summary>
        internal static string VirginAtlanticviosMessageContent {
            get {
                return ResourceManager.GetString("VirginAtlanticviosMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Every &amp;pound;5 into &amp;pound;10.
        /// </summary>
        internal static string VoucherExchange {
            get {
                return ResourceManager.GetString("VoucherExchange", resourceCulture);
            }
        }
    }
}
