
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by CodeSmith.
//
//     Date:    4/6/2009
//     Time:    2:36 
//     Version: 5.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace InstoreClubcardReward.Data
{
	#region UpdateVoucherValue Wrapper
    /// <summary>
    /// This class is a wrapper for the UpdateVoucherValue stored procedure.
    /// </summary>
    public class UpdateVoucherValue
    {
		#region Member Variables
		protected string _connectionString = String.Empty;
        protected SqlConnection _connection = null;
        protected SqlTransaction _transaction = null;
		protected bool _ownsConnection = true;
		protected int _recordsAffected = -1;
		protected int _returnValue = 0;
		protected SqlString _valueCode = SqlString.Null;
		protected bool _valueCodeSet = false;
		protected SqlString _country = SqlString.Null;
		protected bool _countrySet = false;
		protected SqlInt32 _voucherValue = SqlInt32.Null;
		protected bool _voucherValueSet = false;
		#endregion
		
		#region Constructors
		public UpdateVoucherValue()
		{
		}
		
		public UpdateVoucherValue(string connectionString)
		{
			this.ConnectionString = connectionString;
		}
		
		public UpdateVoucherValue(SqlConnection connection)
		{
			this.Connection = connection;
		}
		
		public UpdateVoucherValue(SqlConnection connection, SqlTransaction transaction)
		{
			this.Connection = connection;
			this.Transaction = transaction;
		}
		#endregion
		
		#region Public Properties
		/// <summary>
		/// The connection string to use when executing the UpdateVoucherValue stored procedure.
		/// </summary>
		public string ConnectionString
		{
			get {return _connectionString;}
			set {_connectionString = value;}
		}
        
        /// <summary>
        /// The connection to use when executing the UpdateVoucherValue stored procedure.
        /// If this is not null, it will be used instead of creating a new connection.
        /// </summary>
        public SqlConnection Connection
        {
            get { return _connection; }
            set { _connection = value; }
        }
		
        /// <summary>
        /// The transaction to use when executing the UpdateVoucherValue stored procedure.
        /// If this is not null, the stored procedure will be executing within the transaction.
        /// </summary>
        public SqlTransaction Transaction
        {
            get { return _transaction; }
            set { _transaction = value; }
        }
		
		/// <summary>
		/// Gets the return value from the UpdateVoucherValue stored procedure.
		/// </summary>
		public int ReturnValue
		{
			get {return _returnValue;}
		}
		
		/// <summary>
		/// Gets the number of rows changed, inserted, or deleted by execution of the UpdateVoucherValue stored procedure.
		/// </summary>
		public int RecordsAffected
		{
			get {return _recordsAffected;}
		}
		
		/// <summary>
		/// 
		/// </summary>
		public SqlString ValueCode
		{
			get {return _valueCode;}
			set
			{
				_valueCode = value;
				_valueCodeSet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlString Country
		{
			get {return _country;}
			set
			{
				_country = value;
				_countrySet = true;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public SqlInt32 VoucherValue
		{
			get {return _voucherValue;}
			set
			{
				_voucherValue = value;
				_voucherValueSet = true;
			}
		}
		#endregion
		
		#region Helper Methods
        private SqlConnection GetConnection()
        {
            if (this.Connection != null)
            {
				_ownsConnection = false;
                return this.Connection;
            }
            else
            {
 				System.Diagnostics.Debug.Assert(this.ConnectionString.Length != 0, "You must first set the ConnectioString property before calling an Execute method.");
            	return new SqlConnection(this.ConnectionString);
            }
        }
		#endregion
		
		#region Execute Methods
		/// <summary>
		/// This method calls the UpdateVoucherValue stored procedure.
		/// </summary>
		public virtual void Execute()
		{
			SqlCommand cmd = new SqlCommand();
			
			SqlConnection cn = this.GetConnection();
			
			try
			{
				cmd.Connection = cn;
				cmd.Transaction = this.Transaction;
				cmd.CommandText = "[dbo].[UpdateVoucherValue]";
				cmd.CommandType = CommandType.StoredProcedure;
				
				#region Populate Parameters
				SqlParameter prmReturnValue = cmd.Parameters.Add("@RETURN_VALUE", SqlDbType.Int);
				prmReturnValue.Direction = ParameterDirection.ReturnValue;
				
				SqlParameter prmValueCode = cmd.Parameters.Add("@ValueCode", SqlDbType.Char);
				prmValueCode.Direction = ParameterDirection.Input;
					prmValueCode.Size = 3;
				if (_valueCodeSet == true || this.ValueCode.IsNull == false)
				{
					prmValueCode.Value = this.ValueCode;
				}
				
				SqlParameter prmCountry = cmd.Parameters.Add("@Country", SqlDbType.VarChar);
				prmCountry.Direction = ParameterDirection.Input;
					prmCountry.Size = 3;
				if (_countrySet == true || this.Country.IsNull == false)
				{
					prmCountry.Value = this.Country;
				}
				
				SqlParameter prmVoucherValue = cmd.Parameters.Add("@VoucherValue", SqlDbType.Int);
				prmVoucherValue.Direction = ParameterDirection.Input;
				if (_voucherValueSet == true || this.VoucherValue.IsNull == false)
				{
					prmVoucherValue.Value = this.VoucherValue;
				}
				#endregion
				
				#region Execute Command
				if (cn.State != ConnectionState.Open) cn.Open();
				_recordsAffected = cmd.ExecuteNonQuery();
				#endregion
				
				#region Get Output Parameters
				if (prmReturnValue.Value != null && prmReturnValue.Value != DBNull.Value)
				{
					_returnValue = (int)prmReturnValue.Value;
				}
				
				#endregion
			}
			finally
			{
				if (_ownsConnection)
				{
					if (cn.State == ConnectionState.Open)
					{
						cn.Close();
					}
					
					cn.Dispose();
				}
				cmd.Dispose();
			}
		}
		
		/// <summary>
		/// This method calls the UpdateVoucherValue stored procedure.
		/// </summary>
		/// <param name="connectionString">The connection string to use</param>
		/// <param name="valueCode"></param>
		/// <param name="country"></param>
		/// <param name="voucherValue"></param>
		public static void Execute(
				#region Parameters
				string connectionString,
				SqlString valueCode,
				SqlString country,
				SqlInt32 voucherValue
				#endregion
		    )
		{
			UpdateVoucherValue updateVoucherValue = new UpdateVoucherValue();
			
			#region Assign Property Values
			updateVoucherValue.ConnectionString = connectionString;
			updateVoucherValue.ValueCode = valueCode;
			updateVoucherValue.Country = country;
			updateVoucherValue.VoucherValue = voucherValue;
			#endregion
			
			updateVoucherValue.Execute();
			
			#region Get Property Values
			
			#endregion
		}
		#endregion
	}
	#endregion
}

