//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyEntityServiceLayer.ProcessFD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessFD.IProcessFDRequest")]
    public interface IProcessFDRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFDRequest/ApplicationCheck", ReplyAction="http://tempuri.org/IProcessFDRequest/ApplicationCheckResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IProcessFDRequest/ApplicationCheckExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int ApplicationCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFDRequest/BalanceEnquiry", ReplyAction="http://tempuri.org/IProcessFDRequest/BalanceEnquiryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IProcessFDRequest/BalanceEnquiryExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int BalanceEnquiry(out float reponse, long ClubcardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFDRequest/LoadRewards", ReplyAction="http://tempuri.org/IProcessFDRequest/LoadRewardsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IProcessFDRequest/LoadRewardsExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int LoadRewards(long ClubcardNumber, int AmountLoaded);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessFDRequest/ReportLostStolen", ReplyAction="http://tempuri.org/IProcessFDRequest/ReportLostStolenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IProcessFDRequest/ReportLostStolenExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int ReportLostStolen(long ClubcardNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProcessFDRequestChannel : LoyaltyEntityServiceLayer.ProcessFD.IProcessFDRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProcessFDRequestClient : System.ServiceModel.ClientBase<LoyaltyEntityServiceLayer.ProcessFD.IProcessFDRequest>, LoyaltyEntityServiceLayer.ProcessFD.IProcessFDRequest {
        
        public ProcessFDRequestClient() {
        }
        
        public ProcessFDRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessFDRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessFDRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessFDRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ApplicationCheck() {
            return base.Channel.ApplicationCheck();
        }
        
        public int BalanceEnquiry(out float reponse, long ClubcardNumber) {
            return base.Channel.BalanceEnquiry(out reponse, ClubcardNumber);
        }
        
        public int LoadRewards(long ClubcardNumber, int AmountLoaded) {
            return base.Channel.LoadRewards(ClubcardNumber, AmountLoaded);
        }
        
        public int ReportLostStolen(long ClubcardNumber) {
            return base.Channel.ReportLostStolen(ClubcardNumber);
        }
    }
}
