//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1873
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1873.
// 
#pragma warning disable 1591

namespace CCOHostIntegrationService.SVServiceReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessagingWebServiceSoap", Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class MessagingWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateOfflineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReverseStatusChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReverseStatusChangeExOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProvideHouseholdDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessVouchersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessVouchersExOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessDoubleUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetRewardDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetUnusedVoucherDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetUsedVoucherDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetVoucherValueForHouseholdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRewardDetailsMilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClubcardOnlineGetVoucherValueForAllCPSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MessagingWebService() {
            this.Url = global::CCOHostIntegrationService.Properties.Settings.Default.CCOHostIntegrationService_SVServiceReference_MessagingWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateCompletedEventHandler ValidateCompleted;
        
        /// <remarks/>
        public event ValidateOfflineCompletedEventHandler ValidateOfflineCompleted;
        
        /// <remarks/>
        public event ReverseStatusChangeCompletedEventHandler ReverseStatusChangeCompleted;
        
        /// <remarks/>
        public event ReverseStatusChangeExCompletedEventHandler ReverseStatusChangeExCompleted;
        
        /// <remarks/>
        public event ProvideHouseholdDetailsCompletedEventHandler ProvideHouseholdDetailsCompleted;
        
        /// <remarks/>
        public event ProcessVouchersCompletedEventHandler ProcessVouchersCompleted;
        
        /// <remarks/>
        public event ProcessVouchersExCompletedEventHandler ProcessVouchersExCompleted;
        
        /// <remarks/>
        public event ProcessDoubleUpCompletedEventHandler ProcessDoubleUpCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetRewardDetailsCompletedEventHandler ClubcardOnlineGetRewardDetailsCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetUnusedVoucherDetailsCompletedEventHandler ClubcardOnlineGetUnusedVoucherDetailsCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetUsedVoucherDetailsCompletedEventHandler ClubcardOnlineGetUsedVoucherDetailsCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompletedEventHandler ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompletedEventHandler ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetVoucherValueForHouseholdCompletedEventHandler ClubcardOnlineGetVoucherValueForHouseholdCompleted;
        
        /// <remarks/>
        public event GetRewardDetailsMilesCompletedEventHandler GetRewardDetailsMilesCompleted;
        
        /// <remarks/>
        public event ClubcardOnlineGetVoucherValueForAllCPSCompletedEventHandler ClubcardOnlineGetVoucherValueForAllCPSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/Validate", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Validate(string posrequestXml, string SessionId) {
            object[] results = this.Invoke("Validate", new object[] {
                        posrequestXml,
                        SessionId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateAsync(string posrequestXml, string SessionId) {
            this.ValidateAsync(posrequestXml, SessionId, null);
        }
        
        /// <remarks/>
        public void ValidateAsync(string posrequestXml, string SessionId, object userState) {
            if ((this.ValidateOperationCompleted == null)) {
                this.ValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateOperationCompleted);
            }
            this.InvokeAsync("Validate", new object[] {
                        posrequestXml,
                        SessionId}, this.ValidateOperationCompleted, userState);
        }
        
        private void OnValidateOperationCompleted(object arg) {
            if ((this.ValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateCompleted(this, new ValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ValidateOffline", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidateOffline(string offLineSmartVoucherMessage) {
            object[] results = this.Invoke("ValidateOffline", new object[] {
                        offLineSmartVoucherMessage});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateOfflineAsync(string offLineSmartVoucherMessage) {
            this.ValidateOfflineAsync(offLineSmartVoucherMessage, null);
        }
        
        /// <remarks/>
        public void ValidateOfflineAsync(string offLineSmartVoucherMessage, object userState) {
            if ((this.ValidateOfflineOperationCompleted == null)) {
                this.ValidateOfflineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateOfflineOperationCompleted);
            }
            this.InvokeAsync("ValidateOffline", new object[] {
                        offLineSmartVoucherMessage}, this.ValidateOfflineOperationCompleted, userState);
        }
        
        private void OnValidateOfflineOperationCompleted(object arg) {
            if ((this.ValidateOfflineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateOfflineCompleted(this, new ValidateOfflineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ReverseStatusChange", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReverseStatusChange(string voucherIdentifier, System.DateTime transactionDateStamp) {
            object[] results = this.Invoke("ReverseStatusChange", new object[] {
                        voucherIdentifier,
                        transactionDateStamp});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReverseStatusChangeAsync(string voucherIdentifier, System.DateTime transactionDateStamp) {
            this.ReverseStatusChangeAsync(voucherIdentifier, transactionDateStamp, null);
        }
        
        /// <remarks/>
        public void ReverseStatusChangeAsync(string voucherIdentifier, System.DateTime transactionDateStamp, object userState) {
            if ((this.ReverseStatusChangeOperationCompleted == null)) {
                this.ReverseStatusChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseStatusChangeOperationCompleted);
            }
            this.InvokeAsync("ReverseStatusChange", new object[] {
                        voucherIdentifier,
                        transactionDateStamp}, this.ReverseStatusChangeOperationCompleted, userState);
        }
        
        private void OnReverseStatusChangeOperationCompleted(object arg) {
            if ((this.ReverseStatusChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReverseStatusChangeCompleted(this, new ReverseStatusChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ReverseStatusChangeEx", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ReverseStatusChangeEx(string voucherIdentifier, System.DateTime transactionDateStamp, bool onlineIndicator, string redemptionChannel) {
            object[] results = this.Invoke("ReverseStatusChangeEx", new object[] {
                        voucherIdentifier,
                        transactionDateStamp,
                        onlineIndicator,
                        redemptionChannel});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ReverseStatusChangeExAsync(string voucherIdentifier, System.DateTime transactionDateStamp, bool onlineIndicator, string redemptionChannel) {
            this.ReverseStatusChangeExAsync(voucherIdentifier, transactionDateStamp, onlineIndicator, redemptionChannel, null);
        }
        
        /// <remarks/>
        public void ReverseStatusChangeExAsync(string voucherIdentifier, System.DateTime transactionDateStamp, bool onlineIndicator, string redemptionChannel, object userState) {
            if ((this.ReverseStatusChangeExOperationCompleted == null)) {
                this.ReverseStatusChangeExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReverseStatusChangeExOperationCompleted);
            }
            this.InvokeAsync("ReverseStatusChangeEx", new object[] {
                        voucherIdentifier,
                        transactionDateStamp,
                        onlineIndicator,
                        redemptionChannel}, this.ReverseStatusChangeExOperationCompleted, userState);
        }
        
        private void OnReverseStatusChangeExOperationCompleted(object arg) {
            if ((this.ReverseStatusChangeExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReverseStatusChangeExCompleted(this, new ReverseStatusChangeExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ProvideHouseholdDetails", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tesco.com")]
        public HouseholdDetailResponse ProvideHouseholdDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.tesco.com")] HouseholdRequest householdRequest) {
            object[] results = this.Invoke("ProvideHouseholdDetails", new object[] {
                        householdRequest});
            return ((HouseholdDetailResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProvideHouseholdDetailsAsync(HouseholdRequest householdRequest) {
            this.ProvideHouseholdDetailsAsync(householdRequest, null);
        }
        
        /// <remarks/>
        public void ProvideHouseholdDetailsAsync(HouseholdRequest householdRequest, object userState) {
            if ((this.ProvideHouseholdDetailsOperationCompleted == null)) {
                this.ProvideHouseholdDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProvideHouseholdDetailsOperationCompleted);
            }
            this.InvokeAsync("ProvideHouseholdDetails", new object[] {
                        householdRequest}, this.ProvideHouseholdDetailsOperationCompleted, userState);
        }
        
        private void OnProvideHouseholdDetailsOperationCompleted(object arg) {
            if ((this.ProvideHouseholdDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProvideHouseholdDetailsCompleted(this, new ProvideHouseholdDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ProcessVouchers", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessVouchers(string requestXml, bool ghsFlag) {
            object[] results = this.Invoke("ProcessVouchers", new object[] {
                        requestXml,
                        ghsFlag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessVouchersAsync(string requestXml, bool ghsFlag) {
            this.ProcessVouchersAsync(requestXml, ghsFlag, null);
        }
        
        /// <remarks/>
        public void ProcessVouchersAsync(string requestXml, bool ghsFlag, object userState) {
            if ((this.ProcessVouchersOperationCompleted == null)) {
                this.ProcessVouchersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessVouchersOperationCompleted);
            }
            this.InvokeAsync("ProcessVouchers", new object[] {
                        requestXml,
                        ghsFlag}, this.ProcessVouchersOperationCompleted, userState);
        }
        
        private void OnProcessVouchersOperationCompleted(object arg) {
            if ((this.ProcessVouchersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessVouchersCompleted(this, new ProcessVouchersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ProcessVouchersEx", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DotComSmartVoucherResponse ProcessVouchersEx(DotComSmartVoucherRequest dcSVReq) {
            object[] results = this.Invoke("ProcessVouchersEx", new object[] {
                        dcSVReq});
            return ((DotComSmartVoucherResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessVouchersExAsync(DotComSmartVoucherRequest dcSVReq) {
            this.ProcessVouchersExAsync(dcSVReq, null);
        }
        
        /// <remarks/>
        public void ProcessVouchersExAsync(DotComSmartVoucherRequest dcSVReq, object userState) {
            if ((this.ProcessVouchersExOperationCompleted == null)) {
                this.ProcessVouchersExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessVouchersExOperationCompleted);
            }
            this.InvokeAsync("ProcessVouchersEx", new object[] {
                        dcSVReq}, this.ProcessVouchersExOperationCompleted, userState);
        }
        
        private void OnProcessVouchersExOperationCompleted(object arg) {
            if ((this.ProcessVouchersExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessVouchersExCompleted(this, new ProcessVouchersExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ProcessDoubleUp", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessDoubleUp(string durequestXml) {
            object[] results = this.Invoke("ProcessDoubleUp", new object[] {
                        durequestXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDoubleUpAsync(string durequestXml) {
            this.ProcessDoubleUpAsync(durequestXml, null);
        }
        
        /// <remarks/>
        public void ProcessDoubleUpAsync(string durequestXml, object userState) {
            if ((this.ProcessDoubleUpOperationCompleted == null)) {
                this.ProcessDoubleUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDoubleUpOperationCompleted);
            }
            this.InvokeAsync("ProcessDoubleUp", new object[] {
                        durequestXml}, this.ProcessDoubleUpOperationCompleted, userState);
        }
        
        private void OnProcessDoubleUpOperationCompleted(object arg) {
            if ((this.ProcessDoubleUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDoubleUpCompleted(this, new ProcessDoubleUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetRewardDetails", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetRewardDetails(string ClubcardNumber) {
            object[] results = this.Invoke("ClubcardOnlineGetRewardDetails", new object[] {
                        ClubcardNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetRewardDetailsAsync(string ClubcardNumber) {
            this.ClubcardOnlineGetRewardDetailsAsync(ClubcardNumber, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetRewardDetailsAsync(string ClubcardNumber, object userState) {
            if ((this.ClubcardOnlineGetRewardDetailsOperationCompleted == null)) {
                this.ClubcardOnlineGetRewardDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetRewardDetailsOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetRewardDetails", new object[] {
                        ClubcardNumber}, this.ClubcardOnlineGetRewardDetailsOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetRewardDetailsOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetRewardDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetRewardDetailsCompleted(this, new ClubcardOnlineGetRewardDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetUnusedVoucherDetails", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetUnusedVoucherDetails(string ClubcardNumber) {
            object[] results = this.Invoke("ClubcardOnlineGetUnusedVoucherDetails", new object[] {
                        ClubcardNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUnusedVoucherDetailsAsync(string ClubcardNumber) {
            this.ClubcardOnlineGetUnusedVoucherDetailsAsync(ClubcardNumber, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUnusedVoucherDetailsAsync(string ClubcardNumber, object userState) {
            if ((this.ClubcardOnlineGetUnusedVoucherDetailsOperationCompleted == null)) {
                this.ClubcardOnlineGetUnusedVoucherDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetUnusedVoucherDetailsOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetUnusedVoucherDetails", new object[] {
                        ClubcardNumber}, this.ClubcardOnlineGetUnusedVoucherDetailsOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetUnusedVoucherDetailsOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetUnusedVoucherDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetUnusedVoucherDetailsCompleted(this, new ClubcardOnlineGetUnusedVoucherDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetUsedVoucherDetails", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetUsedVoucherDetails(string ClubcardNumber) {
            object[] results = this.Invoke("ClubcardOnlineGetUsedVoucherDetails", new object[] {
                        ClubcardNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUsedVoucherDetailsAsync(string ClubcardNumber) {
            this.ClubcardOnlineGetUsedVoucherDetailsAsync(ClubcardNumber, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUsedVoucherDetailsAsync(string ClubcardNumber, object userState) {
            if ((this.ClubcardOnlineGetUsedVoucherDetailsOperationCompleted == null)) {
                this.ClubcardOnlineGetUsedVoucherDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetUsedVoucherDetailsOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetUsedVoucherDetails", new object[] {
                        ClubcardNumber}, this.ClubcardOnlineGetUsedVoucherDetailsOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetUsedVoucherDetailsOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetUsedVoucherDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetUsedVoucherDetailsCompleted(this, new ClubcardOnlineGetUsedVoucherDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetUnusedVoucherDetailsBasedOnCP" +
            "Number", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumber(string ClubcardNumber, int CollectionPeriodNumber) {
            object[] results = this.Invoke("ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumber", new object[] {
                        ClubcardNumber,
                        CollectionPeriodNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberAsync(string ClubcardNumber, int CollectionPeriodNumber) {
            this.ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberAsync(ClubcardNumber, CollectionPeriodNumber, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberAsync(string ClubcardNumber, int CollectionPeriodNumber, object userState) {
            if ((this.ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberOperationCompleted == null)) {
                this.ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumber", new object[] {
                        ClubcardNumber,
                        CollectionPeriodNumber}, this.ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompleted(this, new ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNu" +
            "mber", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumber(string ClubcardNumber, int CollectionPeriodNumber) {
            object[] results = this.Invoke("ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumber", new object[] {
                        ClubcardNumber,
                        CollectionPeriodNumber});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberAsync(string ClubcardNumber, int CollectionPeriodNumber) {
            this.ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberAsync(ClubcardNumber, CollectionPeriodNumber, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberAsync(string ClubcardNumber, int CollectionPeriodNumber, object userState) {
            if ((this.ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberOperationCompleted == null)) {
                this.ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumber", new object[] {
                        ClubcardNumber,
                        CollectionPeriodNumber}, this.ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompleted(this, new ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetVoucherValueForHousehold", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetVoucherValueForHousehold(string Household_ID, string CPStartDate, string CPEndDate) {
            object[] results = this.Invoke("ClubcardOnlineGetVoucherValueForHousehold", new object[] {
                        Household_ID,
                        CPStartDate,
                        CPEndDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetVoucherValueForHouseholdAsync(string Household_ID, string CPStartDate, string CPEndDate) {
            this.ClubcardOnlineGetVoucherValueForHouseholdAsync(Household_ID, CPStartDate, CPEndDate, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetVoucherValueForHouseholdAsync(string Household_ID, string CPStartDate, string CPEndDate, object userState) {
            if ((this.ClubcardOnlineGetVoucherValueForHouseholdOperationCompleted == null)) {
                this.ClubcardOnlineGetVoucherValueForHouseholdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetVoucherValueForHouseholdOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetVoucherValueForHousehold", new object[] {
                        Household_ID,
                        CPStartDate,
                        CPEndDate}, this.ClubcardOnlineGetVoucherValueForHouseholdOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetVoucherValueForHouseholdOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetVoucherValueForHouseholdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetVoucherValueForHouseholdCompleted(this, new ClubcardOnlineGetVoucherValueForHouseholdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/GetRewardDetailsMiles", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRewardDetailsMiles(string ClubcardNumber, int ReasonCode) {
            object[] results = this.Invoke("GetRewardDetailsMiles", new object[] {
                        ClubcardNumber,
                        ReasonCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRewardDetailsMilesAsync(string ClubcardNumber, int ReasonCode) {
            this.GetRewardDetailsMilesAsync(ClubcardNumber, ReasonCode, null);
        }
        
        /// <remarks/>
        public void GetRewardDetailsMilesAsync(string ClubcardNumber, int ReasonCode, object userState) {
            if ((this.GetRewardDetailsMilesOperationCompleted == null)) {
                this.GetRewardDetailsMilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRewardDetailsMilesOperationCompleted);
            }
            this.InvokeAsync("GetRewardDetailsMiles", new object[] {
                        ClubcardNumber,
                        ReasonCode}, this.GetRewardDetailsMilesOperationCompleted, userState);
        }
        
        private void OnGetRewardDetailsMilesOperationCompleted(object arg) {
            if ((this.GetRewardDetailsMilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRewardDetailsMilesCompleted(this, new GetRewardDetailsMilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Tesco.com/SmartVouchers/ClubcardOnlineGetVoucherValueForAllCPS", RequestNamespace="http://www.Tesco.com/SmartVouchers", ResponseNamespace="http://www.Tesco.com/SmartVouchers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ClubcardOnlineGetVoucherValueForAllCPS(string Clubcard_Number, string CPStartDate, string CPEndDate) {
            object[] results = this.Invoke("ClubcardOnlineGetVoucherValueForAllCPS", new object[] {
                        Clubcard_Number,
                        CPStartDate,
                        CPEndDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetVoucherValueForAllCPSAsync(string Clubcard_Number, string CPStartDate, string CPEndDate) {
            this.ClubcardOnlineGetVoucherValueForAllCPSAsync(Clubcard_Number, CPStartDate, CPEndDate, null);
        }
        
        /// <remarks/>
        public void ClubcardOnlineGetVoucherValueForAllCPSAsync(string Clubcard_Number, string CPStartDate, string CPEndDate, object userState) {
            if ((this.ClubcardOnlineGetVoucherValueForAllCPSOperationCompleted == null)) {
                this.ClubcardOnlineGetVoucherValueForAllCPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClubcardOnlineGetVoucherValueForAllCPSOperationCompleted);
            }
            this.InvokeAsync("ClubcardOnlineGetVoucherValueForAllCPS", new object[] {
                        Clubcard_Number,
                        CPStartDate,
                        CPEndDate}, this.ClubcardOnlineGetVoucherValueForAllCPSOperationCompleted, userState);
        }
        
        private void OnClubcardOnlineGetVoucherValueForAllCPSOperationCompleted(object arg) {
            if ((this.ClubcardOnlineGetVoucherValueForAllCPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClubcardOnlineGetVoucherValueForAllCPSCompleted(this, new ClubcardOnlineGetVoucherValueForAllCPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class HouseholdRequest {
        
        private string transactionIDField;
        
        private System.DateTime transactionDateTimeField;
        
        private string sourceField;
        
        private HouseholdDetailRequest requestField;
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                this.transactionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public HouseholdDetailRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class HouseholdDetailRequest {
        
        private string requestIDField;
        
        private int requestTypeField;
        
        private string alphaNumericIDField;
        
        private string voucherNoField;
        
        private string clubcardNoField;
        
        private string deliveryPostcodeField;
        
        private int orderNoField;
        
        private bool orderNoFieldSpecified;
        
        private int storeNoField;
        
        private string channelField;
        
        private string virtualStoreField;
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AlphaNumericID {
            get {
                return this.alphaNumericIDField;
            }
            set {
                this.alphaNumericIDField = value;
            }
        }
        
        /// <remarks/>
        public string VoucherNo {
            get {
                return this.voucherNoField;
            }
            set {
                this.voucherNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClubcardNo {
            get {
                return this.clubcardNoField;
            }
            set {
                this.clubcardNoField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryPostcode {
            get {
                return this.deliveryPostcodeField;
            }
            set {
                this.deliveryPostcodeField = value;
            }
        }
        
        /// <remarks/>
        public int OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderNoSpecified {
            get {
                return this.orderNoFieldSpecified;
            }
            set {
                this.orderNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int StoreNo {
            get {
                return this.storeNoField;
            }
            set {
                this.storeNoField = value;
            }
        }
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string VirtualStore {
            get {
                return this.virtualStoreField;
            }
            set {
                this.virtualStoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class DotComSmartVoucherResponseResponseVoucherDetailsVoucherUsage {
        
        private int storeNoField;
        
        private string channelField;
        
        private string virtualStoreField;
        
        private string dateTimeField;
        
        /// <remarks/>
        public int StoreNo {
            get {
                return this.storeNoField;
            }
            set {
                this.storeNoField = value;
            }
        }
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string VirtualStore {
            get {
                return this.virtualStoreField;
            }
            set {
                this.virtualStoreField = value;
            }
        }
        
        /// <remarks/>
        public string DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class DotComSmartVoucherResponseResponseVoucherDetails {
        
        private string alphaNumericIDField;
        
        private string voucherNoField;
        
        private int typeField;
        
        private string clubcardNoField;
        
        private int statusField;
        
        private string expiryDateField;
        
        private double valueField;
        
        private DotComSmartVoucherResponseResponseVoucherDetailsVoucherUsage voucherUsageField;
        
        /// <remarks/>
        public string AlphaNumericID {
            get {
                return this.alphaNumericIDField;
            }
            set {
                this.alphaNumericIDField = value;
            }
        }
        
        /// <remarks/>
        public string VoucherNo {
            get {
                return this.voucherNoField;
            }
            set {
                this.voucherNoField = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ClubcardNo {
            get {
                return this.clubcardNoField;
            }
            set {
                this.clubcardNoField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public DotComSmartVoucherResponseResponseVoucherDetailsVoucherUsage VoucherUsage {
            get {
                return this.voucherUsageField;
            }
            set {
                this.voucherUsageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class DotComSmartVoucherResponseResponse {
        
        private string requestIDField;
        
        private int responseCodeField;
        
        private DotComSmartVoucherResponseResponseVoucherDetails voucherDetailsField;
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public DotComSmartVoucherResponseResponseVoucherDetails VoucherDetails {
            get {
                return this.voucherDetailsField;
            }
            set {
                this.voucherDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class DotComSmartVoucherResponse {
        
        private string transactionIDField;
        
        private string transactionDateTimeField;
        
        private int transactionResponseCodeField;
        
        private DotComSmartVoucherResponseResponse[] responseField;
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                this.transactionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionResponseCode {
            get {
                return this.transactionResponseCodeField;
            }
            set {
                this.transactionResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response")]
        public DotComSmartVoucherResponseResponse[] Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class DotComSmartVoucherRequestRequest {
        
        private string requestIDField;
        
        private int requestTypeField;
        
        private string alphaNumericIDField;
        
        private string voucherNoField;
        
        private string clubcardNoField;
        
        private string deliveryPostcodeField;
        
        private string orderNoField;
        
        private string storeNoField;
        
        private string channelField;
        
        private string virtualStoreField;
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AlphaNumericID {
            get {
                return this.alphaNumericIDField;
            }
            set {
                this.alphaNumericIDField = value;
            }
        }
        
        /// <remarks/>
        public string VoucherNo {
            get {
                return this.voucherNoField;
            }
            set {
                this.voucherNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClubcardNo {
            get {
                return this.clubcardNoField;
            }
            set {
                this.clubcardNoField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryPostcode {
            get {
                return this.deliveryPostcodeField;
            }
            set {
                this.deliveryPostcodeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string StoreNo {
            get {
                return this.storeNoField;
            }
            set {
                this.storeNoField = value;
            }
        }
        
        /// <remarks/>
        public string Channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        public string VirtualStore {
            get {
                return this.virtualStoreField;
            }
            set {
                this.virtualStoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.Tesco.com/SmartVouchers")]
    public partial class DotComSmartVoucherRequest {
        
        private string transactionIDField;
        
        private string transactionDateTimeField;
        
        private string sourceField;
        
        private DotComSmartVoucherRequestRequest[] requestField;
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                this.transactionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Request")]
        public DotComSmartVoucherRequestRequest[] Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class SmartVoucherDetails {
        
        private string voucherNoField;
        
        private string alphaNumericIDField;
        
        private double valueField;
        
        private string expiryDateField;
        
        private int statusField;
        
        /// <remarks/>
        public string VoucherNo {
            get {
                return this.voucherNoField;
            }
            set {
                this.voucherNoField = value;
            }
        }
        
        /// <remarks/>
        public string AlphaNumericID {
            get {
                return this.alphaNumericIDField;
            }
            set {
                this.alphaNumericIDField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class VendorSpecificDetails {
        
        private int vendorIdField;
        
        private int currentPointsBalanceField;
        
        private string currentPointsBalanceDateField;
        
        private SmartVoucherDetails[] smartVoucherDetailsField;
        
        /// <remarks/>
        public int VendorId {
            get {
                return this.vendorIdField;
            }
            set {
                this.vendorIdField = value;
            }
        }
        
        /// <remarks/>
        public int CurrentPointsBalance {
            get {
                return this.currentPointsBalanceField;
            }
            set {
                this.currentPointsBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentPointsBalanceDate {
            get {
                return this.currentPointsBalanceDateField;
            }
            set {
                this.currentPointsBalanceDateField = value;
            }
        }
        
        /// <remarks/>
        public SmartVoucherDetails[] SmartVoucherDetails {
            get {
                return this.smartVoucherDetailsField;
            }
            set {
                this.smartVoucherDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class ClubcardNumbers {
        
        private string clubcardNumberField;
        
        /// <remarks/>
        public string ClubcardNumber {
            get {
                return this.clubcardNumberField;
            }
            set {
                this.clubcardNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class SuppliedClubcardHolderDetails {
        
        private string titleField;
        
        private string initialsField;
        
        private string forenameField;
        
        private string surnameField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Forename {
            get {
                return this.forenameField;
            }
            set {
                this.forenameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class ClubcardDetails {
        
        private string suppliedClubcardNumberField;
        
        private string suppliedClubcardStatusField;
        
        private string suppliedClubcardTypeField;
        
        private SuppliedClubcardHolderDetails suppliedClubcardHolderDetailsField;
        
        /// <remarks/>
        public string SuppliedClubcardNumber {
            get {
                return this.suppliedClubcardNumberField;
            }
            set {
                this.suppliedClubcardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SuppliedClubcardStatus {
            get {
                return this.suppliedClubcardStatusField;
            }
            set {
                this.suppliedClubcardStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SuppliedClubcardType {
            get {
                return this.suppliedClubcardTypeField;
            }
            set {
                this.suppliedClubcardTypeField = value;
            }
        }
        
        /// <remarks/>
        public SuppliedClubcardHolderDetails SuppliedClubcardHolderDetails {
            get {
                return this.suppliedClubcardHolderDetailsField;
            }
            set {
                this.suppliedClubcardHolderDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class CustomerFlag {
        
        private string contactforMarketResearchField;
        
        private string contactbyPhoneforMarketResearchField;
        
        private string contactonlybyTescoField;
        
        private string contactby3rdpartiesField;
        
        private string diabeticField;
        
        private string vegetarianField;
        
        private string teetotalField;
        
        private string kosherField;
        
        private string halalField;
        
        private string organicField;
        
        private string unicornExclField;
        
        private string householdInPromotionField;
        
        private string babyClubField;
        
        private string toddlerClubField;
        
        private string kidsClubField;
        
        private string wineClubField;
        
        private string future1Field;
        
        private string future2Field;
        
        private string future3Field;
        
        private string future4Field;
        
        /// <remarks/>
        public string ContactforMarketResearch {
            get {
                return this.contactforMarketResearchField;
            }
            set {
                this.contactforMarketResearchField = value;
            }
        }
        
        /// <remarks/>
        public string ContactbyPhoneforMarketResearch {
            get {
                return this.contactbyPhoneforMarketResearchField;
            }
            set {
                this.contactbyPhoneforMarketResearchField = value;
            }
        }
        
        /// <remarks/>
        public string ContactonlybyTesco {
            get {
                return this.contactonlybyTescoField;
            }
            set {
                this.contactonlybyTescoField = value;
            }
        }
        
        /// <remarks/>
        public string Contactby3rdparties {
            get {
                return this.contactby3rdpartiesField;
            }
            set {
                this.contactby3rdpartiesField = value;
            }
        }
        
        /// <remarks/>
        public string Diabetic {
            get {
                return this.diabeticField;
            }
            set {
                this.diabeticField = value;
            }
        }
        
        /// <remarks/>
        public string Vegetarian {
            get {
                return this.vegetarianField;
            }
            set {
                this.vegetarianField = value;
            }
        }
        
        /// <remarks/>
        public string Teetotal {
            get {
                return this.teetotalField;
            }
            set {
                this.teetotalField = value;
            }
        }
        
        /// <remarks/>
        public string Kosher {
            get {
                return this.kosherField;
            }
            set {
                this.kosherField = value;
            }
        }
        
        /// <remarks/>
        public string Halal {
            get {
                return this.halalField;
            }
            set {
                this.halalField = value;
            }
        }
        
        /// <remarks/>
        public string Organic {
            get {
                return this.organicField;
            }
            set {
                this.organicField = value;
            }
        }
        
        /// <remarks/>
        public string UnicornExcl {
            get {
                return this.unicornExclField;
            }
            set {
                this.unicornExclField = value;
            }
        }
        
        /// <remarks/>
        public string HouseholdInPromotion {
            get {
                return this.householdInPromotionField;
            }
            set {
                this.householdInPromotionField = value;
            }
        }
        
        /// <remarks/>
        public string BabyClub {
            get {
                return this.babyClubField;
            }
            set {
                this.babyClubField = value;
            }
        }
        
        /// <remarks/>
        public string ToddlerClub {
            get {
                return this.toddlerClubField;
            }
            set {
                this.toddlerClubField = value;
            }
        }
        
        /// <remarks/>
        public string KidsClub {
            get {
                return this.kidsClubField;
            }
            set {
                this.kidsClubField = value;
            }
        }
        
        /// <remarks/>
        public string WineClub {
            get {
                return this.wineClubField;
            }
            set {
                this.wineClubField = value;
            }
        }
        
        /// <remarks/>
        public string future1 {
            get {
                return this.future1Field;
            }
            set {
                this.future1Field = value;
            }
        }
        
        /// <remarks/>
        public string future2 {
            get {
                return this.future2Field;
            }
            set {
                this.future2Field = value;
            }
        }
        
        /// <remarks/>
        public string future3 {
            get {
                return this.future3Field;
            }
            set {
                this.future3Field = value;
            }
        }
        
        /// <remarks/>
        public string future4 {
            get {
                return this.future4Field;
            }
            set {
                this.future4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class HouseholdDetails {
        
        private string requestIDField;
        
        private int responseCodeField;
        
        private string oLAResponseCodeField;
        
        private string householdStatusCodeField;
        
        private string rewardTypeField;
        
        private string rewardTypeOptinDateField;
        
        private string addressLine1Field;
        
        private string postcodeField;
        
        private string phoneNumberField;
        
        private string emailAddressField;
        
        private CustomerFlag customerFlagField;
        
        private string dealStatusField;
        
        private double dealSpendField;
        
        private string previousDealStatusField;
        
        private double previousDealSpendField;
        
        private double remainingDealsSpendField;
        
        private double averageWeeklyDealsSpendField;
        
        private ClubcardDetails suppliedClubcardDetailsField;
        
        private ClubcardNumbers[] clubcardNumbersField;
        
        private VendorSpecificDetails[] vendorSpecificDetailsField;
        
        private double oldVoucherValueUnredeemedField;
        
        /// <remarks/>
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OLAResponseCode {
            get {
                return this.oLAResponseCodeField;
            }
            set {
                this.oLAResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HouseholdStatusCode {
            get {
                return this.householdStatusCodeField;
            }
            set {
                this.householdStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RewardType {
            get {
                return this.rewardTypeField;
            }
            set {
                this.rewardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RewardTypeOptinDate {
            get {
                return this.rewardTypeOptinDateField;
            }
            set {
                this.rewardTypeOptinDateField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public CustomerFlag CustomerFlag {
            get {
                return this.customerFlagField;
            }
            set {
                this.customerFlagField = value;
            }
        }
        
        /// <remarks/>
        public string DealStatus {
            get {
                return this.dealStatusField;
            }
            set {
                this.dealStatusField = value;
            }
        }
        
        /// <remarks/>
        public double DealSpend {
            get {
                return this.dealSpendField;
            }
            set {
                this.dealSpendField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousDealStatus {
            get {
                return this.previousDealStatusField;
            }
            set {
                this.previousDealStatusField = value;
            }
        }
        
        /// <remarks/>
        public double PreviousDealSpend {
            get {
                return this.previousDealSpendField;
            }
            set {
                this.previousDealSpendField = value;
            }
        }
        
        /// <remarks/>
        public double RemainingDealsSpend {
            get {
                return this.remainingDealsSpendField;
            }
            set {
                this.remainingDealsSpendField = value;
            }
        }
        
        /// <remarks/>
        public double AverageWeeklyDealsSpend {
            get {
                return this.averageWeeklyDealsSpendField;
            }
            set {
                this.averageWeeklyDealsSpendField = value;
            }
        }
        
        /// <remarks/>
        public ClubcardDetails SuppliedClubcardDetails {
            get {
                return this.suppliedClubcardDetailsField;
            }
            set {
                this.suppliedClubcardDetailsField = value;
            }
        }
        
        /// <remarks/>
        public ClubcardNumbers[] ClubcardNumbers {
            get {
                return this.clubcardNumbersField;
            }
            set {
                this.clubcardNumbersField = value;
            }
        }
        
        /// <remarks/>
        public VendorSpecificDetails[] VendorSpecificDetails {
            get {
                return this.vendorSpecificDetailsField;
            }
            set {
                this.vendorSpecificDetailsField = value;
            }
        }
        
        /// <remarks/>
        public double OldVoucherValueUnredeemed {
            get {
                return this.oldVoucherValueUnredeemedField;
            }
            set {
                this.oldVoucherValueUnredeemedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tesco.com")]
    public partial class HouseholdDetailResponse {
        
        private string transactionIDField;
        
        private string transactionDateTimeField;
        
        private int transactionResponseCodeField;
        
        private HouseholdDetails responseField;
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                this.transactionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionResponseCode {
            get {
                return this.transactionResponseCodeField;
            }
            set {
                this.transactionResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        public HouseholdDetails Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ValidateCompletedEventHandler(object sender, ValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ValidateOfflineCompletedEventHandler(object sender, ValidateOfflineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateOfflineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateOfflineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ReverseStatusChangeCompletedEventHandler(object sender, ReverseStatusChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReverseStatusChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReverseStatusChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ReverseStatusChangeExCompletedEventHandler(object sender, ReverseStatusChangeExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReverseStatusChangeExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReverseStatusChangeExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProvideHouseholdDetailsCompletedEventHandler(object sender, ProvideHouseholdDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProvideHouseholdDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProvideHouseholdDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HouseholdDetailResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HouseholdDetailResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProcessVouchersCompletedEventHandler(object sender, ProcessVouchersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessVouchersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessVouchersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProcessVouchersExCompletedEventHandler(object sender, ProcessVouchersExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessVouchersExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessVouchersExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DotComSmartVoucherResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DotComSmartVoucherResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProcessDoubleUpCompletedEventHandler(object sender, ProcessDoubleUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDoubleUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDoubleUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetRewardDetailsCompletedEventHandler(object sender, ClubcardOnlineGetRewardDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetRewardDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetRewardDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetUnusedVoucherDetailsCompletedEventHandler(object sender, ClubcardOnlineGetUnusedVoucherDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetUnusedVoucherDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetUnusedVoucherDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetUsedVoucherDetailsCompletedEventHandler(object sender, ClubcardOnlineGetUsedVoucherDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetUsedVoucherDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetUsedVoucherDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompletedEventHandler(object sender, ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetUnusedVoucherDetailsBasedOnCPNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompletedEventHandler(object sender, ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetUsedVoucherDetailsBasedOnCPNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetVoucherValueForHouseholdCompletedEventHandler(object sender, ClubcardOnlineGetVoucherValueForHouseholdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetVoucherValueForHouseholdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetVoucherValueForHouseholdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetRewardDetailsMilesCompletedEventHandler(object sender, GetRewardDetailsMilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRewardDetailsMilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRewardDetailsMilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ClubcardOnlineGetVoucherValueForAllCPSCompletedEventHandler(object sender, ClubcardOnlineGetVoucherValueForAllCPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClubcardOnlineGetVoucherValueForAllCPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClubcardOnlineGetVoucherValueForAllCPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591