//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyEntityServiceLayer.ExactTargetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://us.tescos.com/m025/integration/emailservice/v1/0", ConfigurationName="ExactTargetService.ExactTargetServiceSoap")]
    public interface ExactTargetServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://us.tescos.com/m025/integration/emailservice/v1/0/SendEmailRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SendEmailRequest(LoyaltyEntityServiceLayer.ExactTargetService.SendEmailRequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://us.tescos.com/m025/integration/emailservice/v1/0")]
    public partial class SendEmailRequestRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendEmailRequestRequestDetails[] detailsField;
        
        private string emailTypeField;
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public SendEmailRequestRequestDetails[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmailType {
            get {
                return this.emailTypeField;
            }
            set {
                this.emailTypeField = value;
                this.RaisePropertyChanged("EmailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://us.tescos.com/m025/integration/emailservice/v1/0")]
    public partial class SendEmailRequestRequestDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ExactTargetServiceSoapChannel : LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExactTargetServiceSoapClient : System.ServiceModel.ClientBase<LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceSoap>, LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceSoap {
        
        public ExactTargetServiceSoapClient() {
        }
        
        public ExactTargetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExactTargetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExactTargetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExactTargetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendEmailRequest(LoyaltyEntityServiceLayer.ExactTargetService.SendEmailRequestRequest request) {
            return base.Channel.SendEmailRequest(request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://us.tescos.com/m025/integration/emailservice/v1/0", ConfigurationName="ExactTargetService.ExactTargetServiceHttpGet")]
    public interface ExactTargetServiceHttpGet {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ExactTargetServiceHttpGetChannel : LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExactTargetServiceHttpGetClient : System.ServiceModel.ClientBase<LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceHttpGet>, LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceHttpGet {
        
        public ExactTargetServiceHttpGetClient() {
        }
        
        public ExactTargetServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExactTargetServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExactTargetServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExactTargetServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://us.tescos.com/m025/integration/emailservice/v1/0", ConfigurationName="ExactTargetService.ExactTargetServiceHttpPost")]
    public interface ExactTargetServiceHttpPost {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ExactTargetServiceHttpPostChannel : LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExactTargetServiceHttpPostClient : System.ServiceModel.ClientBase<LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceHttpPost>, LoyaltyEntityServiceLayer.ExactTargetService.ExactTargetServiceHttpPost {
        
        public ExactTargetServiceHttpPostClient() {
        }
        
        public ExactTargetServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExactTargetServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExactTargetServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExactTargetServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
